# Generated by Django 4.0.3 on 2022-03-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.IntegerField(unique=True)),
                ('lga', models.CharField(max_length=100)),
                ('party', models.TextField(max_length=10)),
                ('candidate_id', models.IntegerField()),
                ('election_id', models.IntegerField()),
            ],
        ),
    ]
