# Generated by Django 4.0.3 on 2022-03-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('avatar', models.ImageField(null=True, upload_to='images/')),
                ('election_id', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=500)),
                ('experience', models.TextField(max_length=5000)),
                ('gender', models.TextField(max_length=10)),
                ('party', models.TextField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
